//---------------------------------------------------------------------------

#include <vcl.h>
#include "Startseite1.h"
#include "Eingabe1.h"
#include "Eingabe2.h"
#include "ergebnis.h"

#pragma hdrstop
//---------------------------------------------------------------------------
USEFORM("Eingabe1.cpp", FormEingabe1);
USEFORM("Eingabe2.cpp", FormEingabe2);
USEFORM("Ergebnis.cpp", FormErgebnis);
USEFORM("Startseite1.cpp", Startseite);
USEFORM("UnvollstEingabe.cpp", FormUnvollstEingabe);
USEFORM("AbfrageZuruecksetzen.cpp", FormZuruecksetzen);
USEFORM("AbfrageAbbruch.cpp", FormAbbrechen);
USEFORM("AbbrechenEingabe1.cpp", FormAbbruchEingabeEins);
USEFORM("FormNichtLoesbar.cpp", FormUnbounded);
USEFORM("Hilfe\About.cpp", AboutBox);
//---------------------------------------------------------------------------
WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int)
{
        try
        {
                 Application->Initialize();
                 Application->HelpFile = "D:\\8.Semester\\AnwBetrSys_Grütz\\Programm01\\Hilfe\\FALLPAUSCHALENHILFE.HLP";
                 Application->CreateForm(__classid(TStartseite), &Startseite);
                 Application->CreateForm(__classid(TFormEingabe1), &FormEingabe1);
                 Application->CreateForm(__classid(TFormEingabe2), &FormEingabe2);
                 Application->CreateForm(__classid(TFormErgebnis), &FormErgebnis);
                 Application->CreateForm(__classid(TFormUnvollstEingabe), &FormUnvollstEingabe);
                 Application->CreateForm(__classid(TFormZuruecksetzen), &FormZuruecksetzen);
                 Application->CreateForm(__classid(TFormAbbrechen), &FormAbbrechen);
                 Application->CreateForm(__classid(TFormAbbruchEingabeEins), &FormAbbruchEingabeEins);
                 Application->CreateForm(__classid(TFormUnbounded), &FormUnbounded);
                 Application->CreateForm(__classid(TAboutBox), &AboutBox);
                 Application->Run();
        }
        catch (Exception &exception)
        {
                 Application->ShowException(&exception);
        }
        catch (...)
        {
                 try
                 {
                         throw Exception("");
                 }
                 catch (Exception &exception)
                 {
                         Application->ShowException(&exception);
                 }
        }
        return 0;
}
//---------------------------------------------------------------------------
